wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697033611.841547
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 19
      - 23
      4: 3.10.9
      5: 0.15.12
      8:
      - 1
      - 4
      - 5
      10:
      - 9
      13: darwin-arm64
runs:
  desc: null
  value: 4
feats:
  desc: null
  value: 100
dropout_rate:
  desc: null
  value: 0.01
latent_dim:
  desc: null
  value: 10
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 256
patience:
  desc: null
  value: 100
optimizer_kwargs:
  desc: null
  value:
    learning_rate: 0.001
optimizer:
  desc: null
  value: RMSprop
model_summary:
  desc: null
  value: None
optimality:
  desc: null
  value: A
